version: "3.8"

services:
    laravel:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: skillbridge-backend
        volumes:
            - ./backend:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    react:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: skillbridge-frontend
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"

    mysql:
        image: mysql:8
        container_name: skillbridge-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: skillbridge
            MYSQL_USER: skilluser
            MYSQL_PASSWORD: skillpass
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
